const generatedGlob = new Bun.Glob("packages/kyoushitsu/src/api/generated/**/*.ts")
const artifactPaths = ["packages/housou/openapi.json", "packages/kyoushitsu/openapi.json"]
const generatedHeader = "// This file is auto-generated by @hey-api/openapi-ts"

async function runGeneration(): Promise<void> {
  const child = Bun.spawn(["bun", "--no-env-file", "run", "contract:generate"], {
    stdout: "inherit",
    stderr: "inherit",
  })
  const exitCode = await child.exited
  if (exitCode !== 0) throw new Error(`contract generation exited with status ${exitCode}`)
}

async function generatedPaths(): Promise<string[]> {
  const paths: string[] = []
  for await (const path of generatedGlob.scan({ cwd: ".", onlyFiles: true })) paths.push(path)
  return paths.sort()
}

async function snapshot(): Promise<Map<string, string>> {
  const paths = [...artifactPaths, ...(await generatedPaths())].sort()
  const result = new Map<string, string>()
  for (const path of paths) {
    const file = Bun.file(path)
    if (!(await file.exists())) throw new Error(`contract output is missing: ${path}`)
    result.set(path, await file.text())
  }
  assertGeneratedBoundary(result)
  return result
}

function assertGeneratedBoundary(files: Map<string, string>): void {
  for (const [path, content] of files) {
    if (!path.startsWith("packages/kyoushitsu/src/api/generated/")) continue
    if (!content.startsWith(generatedHeader)) {
      throw new Error(`generated client file is missing its header: ${path}`)
    }
    if (content.includes("houkago-housou")) {
      throw new Error(`generated client must not import the server App contract: ${path}`)
    }
    if (
      path === "packages/kyoushitsu/src/api/generated/types.gen.ts" &&
      /\b(?:unknown|any)\b/.test(content)
    ) {
      throw new Error(`generated HTTP DTOs contain an untyped schema: ${path}`)
    }
  }
}

function assertEqual(
  first: Map<string, string>,
  second: Map<string, string>,
  message = "contract generation is not deterministic",
): void {
  const paths = [...new Set([...first.keys(), ...second.keys()])].sort()
  const changed = paths.filter((path) => first.get(path) !== second.get(path))
  if (changed.length > 0) {
    throw new Error(`${message}: ${changed.join(", ")}`)
  }
}

const baseline = await snapshot()
await runGeneration()
const first = await snapshot()
await runGeneration()
const second = await snapshot()
assertEqual(first, second)
assertEqual(baseline, second, "checked contract artifacts are stale; run contract:generate")
console.log(`Contract drift check passed: ${first.size} generated files are byte-stable`)
